name: ShellCheck
on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        # note: Double quote array expansions to avoid re-splitting elements. [SC2068]
        # note: Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?. [SC2181]
        env:
          SHELLCHECK_OPTS: -e SC2181 -e SC2068
        with:
          scandir: './kickstart_source_script'
